export default {
    default: {
        angle: 0.1,
        warningMin: 600,
        warningMax: 1000,
        reloadMin: 600,
        reloadMax: 1000,
        health: 2,
        dead: false,
        detect: false,
        warning: null,
        detectRange: 300,
    },
    dog: {
        health: 1,
        dead: false,
    },
    bossGun: {
        angle: 0.1,
        warningMin: 400,
        warningMax: 800,
        reloadMin: 300,
        reloadMax: 500,
        health: 5,
        dead: false,
        detect: false,
        warning: null,
        rapidFire: 7,
        melee: true,
        walk: true
    },
    bossSmg: {
        angle: 0.4,
        warningMin: 300,
        warningMax: 600,
        reloadMin: 200,
        reloadMax: 400,
        health: 5,
        dead: false,
        detect: false,
        warning: null,
        rapidFire: 10,
    },
    bossLauncher: {
        angle: 0.1,
        warningMin: 400,
        warningMax: 800,
        reloadMin: 400,
        reloadMax: 600,
        health: 5,
        dead: false,
        detect: false,
        warning: null,
    },
    bossVan: {
        angle: 0.1,
        warningMin: 300,
        warningMax: 500,
        reloadMin: 200,
        reloadMax: 400,
        health: 8,
        dead: false,
        detect: false,
        warning: null,
        rapidFire: 7,
        deathType: 'bigExplode'
    },
}